### ISSUE TITLE
Checksum verification issue with Eltako esp2 - solved

### ISSUE THREAD

**Issue by BeenThereScrewedUp** [coolchip/node-enocean-esp2#1]
Hi,

I used your node red enocean esp2 package for over a year now. I had to modify it to get a good verification of all valid received data from my Eltako FGW14-USB gateway.

Regards

Lars

This is the diff:
diff --git a/parser.js b/parser.js
index d0db21b..380e935 100644
--- a/parser.js
+++ b/parser.js
@@ -83,11 +83,12 @@ const hexStringToByteArray = function (hex) {
     return bytes;
 };

-const verifyChecksum = function (buf, checksum) {
+const verifyChecksum = function (buf, checksum, hseq) {
     let result = 0;
     for (let index = 0; index < buf.length; index++) {
-        result = (result + buf[index]) % 0xff;
+        result = (result + buf[index]);
     }
+    result = result & 0xff;
     return result === checksum;
 };

@@ -100,7 +101,7 @@ const sliceBuffer = function (buf) {
     telegram.org = buf.readUInt8(3);
     telegram.payload = buf.slice(4, 4 + telegram.length - 2);
     telegram.checksum = buf.readUInt8(4 + telegram.length - 2);
-    telegram.valid = verifyChecksum(buf.slice(2, 4 + telegram.length - 2), telegram.checksum);
+    telegram.valid = verifyChecksum(buf.slice(2, 4 + telegram.length - 2), telegram.checksum, telegram.hseq);
     telegram.dataBytes = telegram.payload.slice(0, 4).toString('hex');
     telegram.idBytes = telegram.payload.slice(4, 8).toString('hex');
     telegram.status = telegram.payload.readUInt8(8);
@@ -233,4 +234,4 @@ const parse = function (buf) {
     return parsed;
 };

**Comment by coolchip** [comment]
Thank you very, very much. Looks great. I'll test it.
I only have one question. What is the parameter "hseq" in const verifyChecksum = function (buf, checksum, **hseq**) for?

**Comment by coolchip** [comment]
implemented theese fix for a while now
