### ISSUE TITLE
Usage example / documentation

### ISSUE THREAD

**Issue by TailwindNL** [coolchip/node-enocean-esp2#4]
I really want to use this nodes in nodered. I've been able to hook up the incoming node and am seeing telegram messages from the Eltako enocean bus, but want to know how to use the output node. How to send telegram messages (format in nodered), more concrete:  how do I control actuators (f.e. fud14 dimmer) from nodered? How to receive feedback from the actuators?

If you could share an example nodered flow with a demonstration of the capabilities that would be great.

Thanks in advance!

Ps. I could not find any documentation. If there is any, a link to it will help me also.

**Comment by Ekristoffe** [comment]
hello, i know this node: https://github.com/coolchip/node-red-contrib-enocean-esp2 is using node-enocean-esp2 for node-red.
I don't know if it can help you by using it or by looking at the source code ...

if you really want to make your own node i think you need to give a buffer with the ESP2 protocol.

**Comment by TailwindNL** [comment]
> hello, i know this node: https://github.com/coolchip/node-red-contrib-enocean-esp2 is using node-enocean-esp2 for node-red.
> I don't know if it can help you by using it or by looking at the source code ...
> 
> if you really want to make your own node i think you need to give a buffer with the ESP2 protocol.

Hello Ekristoffe,

Thank you for replying. I'm referring to https://flows.nodered.org/node/node-red-contrib-enocean-esp2. I do not want to write my own code, I just want to know how to use the "enocean-esp2 out" node. It needs some input. F.e. a json message with certain payload. I just don't know what to send to the output node. A example flow would help me. Or, if you know what data to send I could figure out how to put it in Nodered.

**Comment by coolchip** [comment]
Unfortunatelly sending a package to the bus is hell. You have to make your own package and send it to the node. Till now I had no time to complete this. Here is a sample for one of my roller shutter.

```
[{"id":"7683cc02.39a4e4","type":"enocean-esp2 out","z":"1430f9dc.a36576","name":"","datasource":"eb7ca5ea.f88618","x":410,"y":2120,"wires":[]},{"id":"b2ccd30c.71fcf","type":"function","z":"1430f9dc.a36576","name":"EG","func":"const up =  Buffer.from('a55a0b05100000000000122f3091', 'hex');\nconst down =  Buffer.from('a55a0b05700000000000123030f2', 'hex');\n\nconst payload = msg.payload === true ? up : down;\nnode.send({\n    payload\n});\n","outputs":1,"noerr":0,"x":270,"y":2120,"wires":[["7683cc02.39a4e4"]]},{"id":"c90dae41.b01a1","type":"inject","z":"1430f9dc.a36576","name":"HOCH","props":[{"p":"payload","v":"true","vt":"bool"},{"p":"topic","v":"","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"true","payloadType":"bool","x":90,"y":2120,"wires":[["b2ccd30c.71fcf"]]},{"id":"a4cc25be.75fe18","type":"inject","z":"1430f9dc.a36576","name":"RUNTER","props":[{"p":"payload","v":"false","vt":"bool"},{"p":"topic","v":"","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"false","payloadType":"bool","x":100,"y":2160,"wires":[["b2ccd30c.71fcf"]]},{"id":"eb7ca5ea.f88618","type":"enocean-esp2-connection","sourcetype":"serial","serialport":"/dev/ttyEltako","serialbaud":"57600","databits":"8","parity":"none","stopbits":"1","filepath":"/dev/null"}]
```

**Comment by C-r-e-d-o** [comment]
A short documentation would be great. 
I only want to know how to handle the "enocean-esp2 out" node.

**Comment by coolchip** [comment]
I've added a little bit of information to the readme. Sorry, I'm very busy.

**Comment by TailwindNL** [comment]
Thanks for the effort. I'm still trying to figure out how to create the telegram message to send to the out node to control my FUD14 dimmers.  I have the idea to create a Excel file what will take the input information needed about the device (e.g. a FUD14 dimmer) and outputs a telegram message to control it. This way I can play with the Excel to wrap my head around the whole telegram creation, but even this is a daunting task.
